services:
  grafana:
    image: grafana/otel-lgtm:latest
    ports:
    - "3000:3000"
    - "4317:4317"
    - "4318:4318"

  postgres:
    image: postgres:17.2-alpine3.21
    ports:
    - "5432:5432"

  vault:
    image: hashicorp/vault:1.18
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-root"
    cap_add:
    - IPC_LOCK
