name: Build and Publish

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate Version
      run: |
        echo "TAGS=ghcr.io/${GITHUB_REPOSITORY@L}:$(git rev-parse --short HEAD)"

    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.TAGS }}
